greeting:
  message: "hello"
  http:
    port: 8080
    cors:
      ~: true
      origins: "http://localhost:3000,chrome-extension://*,moz-extension://*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "Content-Type,Authorization"
      exposed-headers: "Content-Disposition"
      access-control-max-age: 24H
    root-path: /
    static-resources:
      enable: true

  native:
    additional-build-args: "--initialize-at-run-time=org.h2.Driver"

  smallrye-openapi:
    path: /swagger
